[package]
name = "miden-prover"
version.workspace = true
description = "Miden VM prover"
documentation = "https://docs.rs/miden-prover"
readme = "README.md"
categories = ["cryptography", "emulators", "no-std"]
keywords = ["miden", "prover", "stark", "zkp"]
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true

[features]
default = ["std"]
async = ["winter-maybe-async/async"]
concurrent = ["std", "miden-processor/concurrent", "winter-prover/concurrent"]
metal = ["dep:miden-gpu", "dep:elsa", "dep:pollster", "concurrent", "std"]
std = ["miden-air/std", "miden-debug-types/std", "miden-processor/std", "winter-prover/std"]

[dependencies]
# air = { package = "miden-air", path = "../air", default-features = false }
# processor = { package = "miden-processor", path = "../processor", default-features = false }

p3-matrix = { branch = "zz/migrate-plonky3", default-features = false, git = "https://github.com/0xMiden/Plonky3/" }
p3-uni-stark = { branch = "zz/migrate-plonky3", default-features = false, git = "https://github.com/0xMiden/Plonky3/", features = [ "parallel" ]}
p3-field = { branch = "zz/migrate-plonky3", default-features = false, git = "https://github.com/0xMiden/Plonky3/" }
p3-merkle-tree = { branch = "zz/migrate-plonky3", default-features = false, git = "https://github.com/0xMiden/Plonky3/" }
p3-commit = { branch = "zz/migrate-plonky3", default-features = false, git = "https://github.com/0xMiden/Plonky3/" }
p3-fri = { branch = "zz/migrate-plonky3", default-features = false, git = "https://github.com/0xMiden/Plonky3/" }
p3-dft = { branch = "zz/migrate-plonky3", default-features = false, git = "https://github.com/0xMiden/Plonky3/", features = [ "parallel" ]}
p3-poseidon2 = { branch = "zz/migrate-plonky3", default-features = false, git = "https://github.com/0xMiden/Plonky3/" }
p3-challenger = { branch = "zz/migrate-plonky3", default-features = false, git = "https://github.com/0xMiden/Plonky3/" }
p3-goldilocks = { branch = "zz/migrate-plonky3", default-features = false, git = "https://github.com/0xMiden/Plonky3/" }
p3-symmetric = { branch = "zz/migrate-plonky3", default-features = false, git = "https://github.com/0xMiden/Plonky3/" }
p3-util = { branch = "zz/migrate-plonky3", default-features = false, git = "https://github.com/0xMiden/Plonky3/", features = [ "parallel" ]}
p3-blake3 = { branch = "zz/migrate-plonky3", default-features = false, git = "https://github.com/0xMiden/Plonky3/" }
p3-keccak = { branch = "zz/migrate-plonky3", default-features = false, git = "https://github.com/0xMiden/Plonky3/" }
p3-maybe-rayon = { branch = "zz/migrate-plonky3", default-features = false, git = "https://github.com/0xMiden/Plonky3/" }
p3-air = { branch = "zz/migrate-plonky3", default-features = false, git = "https://github.com/0xMiden/Plonky3/" }

serde = { version = "1.0", features = ["derive"]}
bincode = "1.3"

rand = "0.9"
# miden-crypto = { version = "0.14", default-features = false }
miden-crypto = { git = "https://github.com/0xMiden/crypto", branch = "zz/migrate-plonky3" }
# Miden dependencies
miden-air.workspace = true
miden-debug-types.workspace = true
miden-processor.workspace = true

# External dependencies
tracing.workspace = true
winter-maybe-async = { version = "0.13", default-features = false }
winter-prover.workspace = true

[target.'cfg(all(target_arch = "aarch64", target_os = "macos"))'.dependencies]
elsa = { version = "1.11", optional = true }
miden-gpu = { version = "0.6", optional = true }
pollster = { version = "0.4", optional = true }
